### ISSUE TITLE
SEQ915 - UTF8 Encoding on TEXT columns

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#2286]
As a developer I would like to convert our database character encoding to utf8mb4 (utf 8 isn't actually utf8 in mysql world) on the key affected TEXT columns (mostly in study and sample metadata) to increase supported user input, and move into this decade, without incurring the additional costs of converting everything

A complete UTF8 migration may be tricky, as preliminary investigation suggests that it has an impact on column size restrictions.

"Caveats: May still run into the size issues above. 

Acceptance: 
- As many TEXT columns updated as possible.
- Defaults for new tables/columns updated (To avoid issues in future)
- No data integrity issues post migration. (Need to validate on production like database)"

**Comment by JamesGlover** [comment]
https://dev.mysql.com/doc/refman/5.7/en/charset-unicode-utf8mb4.html

**Comment by JamesGlover** [comment]
Over time our production and dev schemas have drifted, particularly wrt character encoding. I'm going to begin by updating our schema to match production (minus the odd temporary tableau tables)

**Comment by JamesGlover** [comment]
Fixed up a handful of failing tests which were violating foreign key constraints, and dropped a redundant column which was 'not null' in production, resulting in the need to seed it with arbitrary data.

**Comment by JamesGlover** [comment]
Migrations for study and sample metadata done, and run against production like data (Dump taken for the asset refactor).

Validating data pre and post migration. Study::Metadata shows no changes, currently validating Sample::Metadata. Essentially: Study::Metadata.find_each {|sm| file.puts sm.attributes.inspect } then diffing the output.

**Comment by JamesGlover** [comment]
Need to be a touch careful with the scope of this, as the changes do lock tables.

**Comment by JamesGlover** [comment]
Sample metadata unchanged as well.

**Comment by JamesGlover** [comment]
Comments migrated and validated

**Comment by JamesGlover** [comment]
I've mainly avoided touching other tables at this point due to the fact the change is locking. As this is, we should only really see  a couple of pinch points where manifest processing is delayed by a couple of minutes.

**Comment by JamesGlover** [comment]
Eeep, running against training after a successful local run and get:

```
   (5.6ms)  COMMIT
Migrating to MigrateSampleMetadataToUtf8mb4 (20190815114947)
== 20190815114947 MigrateSampleMetadataToUtf8mb4: migrating ===================
   (16.0ms)  ALTER TABLE sample_metadata CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci

   (36.7ms)  SELECT RELEASE_LOCK('5097237807218583180')
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Index column size too large. The maximum column size is 767 bytes.: ALTER TABLE sample_metadata CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/rack-mini-profiler-1.0.2/lib/patches/db/mysql2.rb:22:in `query'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activesupport-5.1.7/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:213:in `block in execute'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:212:in `execute'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/mysql/database_statements.rb:26:in `execute'
/Users/jg16/projects/james/sequencescape_2/db/migrate/20190815114947_migrate_sample_metadata_to_utf8mb4.rb:8:in `up'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:795:in `exec_migration'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:775:in `block in migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `with_connection'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:774:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:953:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1300:in `ddl_transaction'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1200:in `each'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1148:in `block in migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1148:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1007:in `up'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:985:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/bin/ruby_executable_hooks:24:in `eval'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Index column size too large. The maximum column size is 767 bytes.: ALTER TABLE sample_metadata CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/rack-mini-profiler-1.0.2/lib/patches/db/mysql2.rb:22:in `query'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activesupport-5.1.7/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:213:in `block in execute'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:212:in `execute'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/mysql/database_statements.rb:26:in `execute'
/Users/jg16/projects/james/sequencescape_2/db/migrate/20190815114947_migrate_sample_metadata_to_utf8mb4.rb:8:in `up'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:795:in `exec_migration'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:775:in `block in migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `with_connection'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:774:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:953:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1300:in `ddl_transaction'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1200:in `each'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1148:in `block in migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1148:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1007:in `up'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:985:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/bin/ruby_executable_hooks:24:in `eval'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
Mysql2::Error: Index column size too large. The maximum column size is 767 bytes.
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/rack-mini-profiler-1.0.2/lib/patches/db/mysql2.rb:22:in `query'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activesupport-5.1.7/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:213:in `block in execute'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:212:in `execute'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/mysql/database_statements.rb:26:in `execute'
/Users/jg16/projects/james/sequencescape_2/db/migrate/20190815114947_migrate_sample_metadata_to_utf8mb4.rb:8:in `up'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:795:in `exec_migration'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:775:in `block in migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `with_connection'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:774:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:953:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1300:in `ddl_transaction'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1200:in `each'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1148:in `block in migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1148:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:1007:in `up'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/migration.rb:985:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/activerecord-5.1.7/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/bin/ruby_executable_hooks:24:in `eval'
/Users/jg16/.rvm/gems/ruby-2.5.3@sequencescape-second/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
Which is the same issue seen before. Need to look into this in more detail, some information here, which may be of use. https://railsmachine.com/articles/2017/05/19/converting-a-rails-database-to-utf8mb4.html

**Comment by JamesGlover** [comment]
Ahh, it appears that locally my row format is set to dynamic, whereas on the training and production servers its set to compact.

Few options:
1) Convert columns on a case by case basis. db:schema does support this, but its a bit clunky.
2) Drop the maximum length on our indexed columns to 191.
3) See if we can update the row format on the server to be 'Dynamic.' I'd probably need to check with the DBAs, and it would be nice if we could do this without two table duplications. 

I'm going to contact the DBAs about option 3.

**Comment by JamesGlover** [comment]
DBAs indicate that there will be no issue switching to dynamic, which is apparently the new default for MySQL 5.7 anyway. They are currently overriding this default for our databases to maintain the pre-existing defaults. They've offered to remove this override to ensure all future tables will by dynamic. I've agreed.
