### ISSUE TITLE
GPL-359 optimize plate well creation

### ISSUE THREAD

**Issue by JamesGlover** [sanger/sequencescape#2583]
**User story**
As a user I would like to improve performance of plate creation to reduce waiting time while processing plates.

**Who the primary contacts are for this story**
James Glover

**Acceptance criteria**
1) The well creation process on plates should take advantage of the labware/receptacle split to generate plate wells in a single insert operation.
2) Wells should still have appropriate callbacks run (probably just WH broadcast)
3) The new process should be faster than the original.

**Additional context**
See the #construct! method on the plate-well association (in app/models/plate.rb:41 at time of writing) and use the activerecord-import gem to handle the bulk insert. (Already in the Gemfile) You'll need to check what after_create callbacks are firing on the well and ensure that they trigger correctly.

**Comment by stevieing** [comment]
1. Research the use of performance testing tools to test the optimisation of the well creation.

**Comment by stevieing** [comment]
2. Implement use of the activerecord-import gem to do bulk well creation.

**Comment by stevieing** [comment]
3. Research the plate creation model to see if there are any other ways to refactor the code to speed up bulk well creation.

**Comment by harrietc52** [comment]
Google sheet for performance testing
https://docs.google.com/spreadsheets/d/1ik58_iPAlmcmqBrU8hnHeC4PTJyolK071aw_cxH-Amw/edit#gid=0

**Comment by harrietc52** [comment]
Sequenceflow https://www.lucidchart.com/documents/edit/e2d80e18-6d35-4239-b6a8-d956f265359b/0_0?referringApp=google+drive&beaconFlowId=a86966de8820661d

**Comment by harrietc52** [comment]
<img width="433" alt="Screen Shot 2020-03-31 at 16 01 49" src="https://user-images.githubusercontent.com/11446617/78049413-f3161c80-7372-11ea-841c-51cd5b3f756e.png">

**Comment by harrietc52** [comment]
Further options:
- Continue to use Rails profiling tools to find which steps are slow to target
- Move to api v2
- Use intergration suite to test the time from a users point of view for different steps
- User integration suite to find exactly what communication is happening between Limber and SS
- Move plate/well creation code to a different place that might have a more acceptable time lag
- Check any unused indexes in db
- Check any other unessary joins, pulling back data that isnt required
- Consider using GraphQL
- Refactor own 'map' of well location methods to using something else, eg coordinates
- Check in prod mode, as development mode might be slower
- Check the rendering of Limber aliquotes
- Check for any memory leaks in SS or Limber
- Look into the transfer of material step, not just the creation of plate. As Limber has two steps, create plate and then transfer material


For all the above, implement basic performance tests so we can test the difference

**Comment by stevieing** [comment]
Articles on profiling tools:
https://scoutapm.com/blog/which-rails-profiler-is-right-for-you
https://www.codementor.io/@victor_hazbun/rack-mini-profiler-for-the-win-kq00prump

**Comment by JamesGlover** [comment]
Complete log from integration tests:
```12:45 $ ENVIRONMENT=uat bundle exec rspec

Randomized with seed 56123
Following the high throughput Heron(96-well) pipeline {
  96 well {
    Build tag group ✓ (0.31s)
    Build submission {
      Generate primer panel Primer Panel generated = nCov-2019
✓ (0.42s)
[Heron(96) Submission id = 113955]
    } ✓ (5.48s)
    Build tag layout template ✓ (0.19s)
    Log in ✓ (9.85s)
    Process LHR RT plate (DN623942I) {
      Refreshing until block true ✓ (0.10s)
      Fill in Bravo LHR RT => LHR PCR 1 and 2 ✓ (2.16s)
      Stamp the LHR XP ✓ (5.19s)
    } ✓ (11.77s)
    Process the LHR XP plate (DN623944K) {
      Fill in NX-96 LHR PCR 1 and 2 => LHR XP ✓ (3.69s)
      Stamp the LHR End Prep ✓ (5.83s)
    } ✓ (11.65s)
    Process the LHR End Prep plate (DN623945L) {
      Fill in bravo LHR XP => LHR End Prep ✓ (2.56s)
      Refreshing until block true ✓ (0.07s)
      Fill in bravo LHR End Prep ✓ (2.67s)
      Refreshing until block true ✓ (0.06s)
      Create tag plate ✓ (6.29s)
    } ✓ (18.02s)
    Process the LHR Lib PCR plate (DN623943J) {
      Fill in bravo LHR End Prep => LHR Lib PCR ✓ (2.65s)
    } ✓ (14.70s)
    Process the LHR Lib Pool, XP and Norm tubes for multiplexing
LHR Lib Pool tube = 3981556536670
LHR Lib Pool XP tube = 3981556537684
LB Lib Pool Norm tube = 3981556535666
✓ (23.72s)
  } OK (96.80s)
} (96.80s)
Following the Bespoke Chromium Aggregation and 5p VDJ pipelines {
  96 well {
    Build submission ✓ (5.71s)
    Build tag group ✓ (0.18s)
    Log in ✓ (1.57s)
    Process the LBC Stock plate (DN623946M) {
      Refreshing until block true ✓ (6.62s)
    } ✓ (8.63s)
    Process the LBC Aggregate plate (#<Capybara::Node::Element:0x00007faf3efba938>) {
      Fill in the ten stamp page ✓ (7.40s)
    } ✓ (12.43s)
    Process the LBC Cherrypick plate (Shared) {
      Fill in the ten stamp page ✓ (5.97s)
      Fill in hamilton LBC Aggregate => LBC Cherrypick ✓ (4.59s)
    } ✓ (14.15s)
    Build submission for chromium 5p library creation [5p Submission id = 113957]
✓ (2.15s)
    Build submission for chromium VDJ TCR library creation [TCR Submission id = 113958]
✓ (2.27s)
    Build submission for chromium VDJ BCR library creation [BCR Submission id = 113959]
✓ (1.95s)
    Add concentrations to LBC Cherrypick plate Number of well concentrations written = 90
✓ (1.17s)
    Process the LBC Cherrypick plate (5p GEX) (DN623948O) {
      Refreshing until block true ✓ (18.26s)
      Stamp the LBC 5p GEX Dil ✓ (6.09s)
    } ✓ (24.45s)
    Process the LBC 5p GEX Dil plate (DN623949P) {
      Fill in hamilton LBC Cherrypick => LBC 5p GEX Dil ✓ (3.08s)
      Stamp the LBC 5p GEX Frag 2XP ✓ (4.66s)
    } ✓ (10.57s)
    Process the LBC 5p GEX Frag 2XP plate (DN623950I) {
      Fill in hamilton LBC 5p GEX Dil => LBC 5p GEX Frag 2XP ✓ (2.93s)
    } ✓ (6.31s)
    Process the LBC 5p GEX LigXP plate {
      Fill in the custom tagged plate page ✓ (8.01s)
LBC 5p GEX LigXP = DN623951J
      Fill in hamilton LBC 5p GEX Frag 2XP => LBC 5p GEX LigXP ✓ (2.60s)
      Stamp the LBC 5p GEX PCR 2XP ✓ (6.35s)
    } ✓ (19.73s)
    Process the LBC 5p GEX PCR 2XP plate (DN623952K) ✓ (16.54s)
    Process the LBC 5p GLibPS tubes ✓ (16.64s)
    Process the LBC Cherrypick plate (TCR) (DN623948O) {
      Refreshing until block true ✓ (0.06s)
      Stamp the LBC TCR Dil 1 ✓ (5.08s)
    } ✓ (8.17s)
    Process the LBC TCR Dil 1 plate (DN623953L) {
      Fill in hamilton LBC Cherrypick => LBC TCR Dil 1 ✓ (3.00s)
      Stamp the LBC TCR Enrich1 1XSPRI ✓ (4.48s)
    } ✓ (9.83s)
    Process the LBC TCR Enrich1 1XSPRI plate (DN623955N) {
      Fill in hamilton LBC TCR Dil 1 => LBC TCR Enrich1 1XSPRI ✓ (2.49s)
      Stamp the LBC TCR Enrich2 2XSPRI ✓ (4.09s)
    } ✓ (9.27s)
    Process the LBC TCR Enrich2 2XSPRI plate (DN623956O) {
      Fill in hamilton LBC TCR Enrich1 1XSPRI => LBC TCR Enrich2 2XSPRI ✓ (3.07s)
    } ✓ (5.63s)
    Add concentrations to LBC TCR Enrich2 2XSPRI plate Number of well concentrations written = 42
✓ (0.97s)
    Create the LBC TCR Dil 2 plate {
      Refreshing until block true ✓ (0.05s)
      Stamp the LBC TCR Dil 2 ✓ (5.31s)
    } ✓ (5.36s)
    Process the LBC TCR Dil 2 plate (DN623957P) {
      Fill in hamilton LBC TCR Enrich2 2XSPRI => LBC TCR Dil 2 ✓ (2.27s)
    } ✓ (5.11s)
    Process the LBC TCR Post Lig 1XSPRI plate {
      Fill in the custom tagged plate page ✓ (5.92s)
LBC TCR Post Lig 1XSPRI = DN623958Q
      Fill in hamilton LBC TCR Dil 2 => LBC TCR Post Lig 1XSPRI ✓ (2.30s)
      Stamp the LBC TCR Post PCR ✓ (5.26s)
    } ✓ (15.69s)
    Process the LBC TCR Post PCR plate (DN623959R) ✓ (12.32s)
    Process the LBC TCR LibPS tubes ✓ (12.37s)
    Process the LBC Cherrypick plate (DN623948O) {
      Refreshing until block true ✓ (0.04s)
      Stamp the LBC BCR Dil 1 ✓ (5.01s)
    } ✓ (8.16s)
    Process the LBC BCR Dil 1 plate (DN623960K) {
      Fill in hamilton LBC Cherrypick => LBC BCR Dil 1 ✓ (2.85s)
      Stamp the LBC BCR Enrich1 1XSPRI ✓ (3.81s)
    } ✓ (8.68s)
    Process the LBC BCR Enrich1 1XSPRI plate (DN623961L) {
      Fill in hamilton LBC BCR Dil 1 => LBC BCR Enrich1 1XSPRI ✓ (2.86s)
      Stamp the LBC BCR Enrich2 2XSPRI ✓ (4.15s)
    } ✓ (9.23s)
    Process the LBC BCR Enrich2 2XSPRI plate (DN623962M) {
      Fill in hamilton LBC BCR Enrich1 1XSPRI => LBC BCR Enrich2 2XSPRI ✓ (2.73s)
    } ✓ (4.84s)
    Add concentrations to LBC BCR Enrich2 2XSPRI plate Number of well concentrations written = 35
✓ (0.80s)
    Create the LBC BCR Dil 2 plate {
      Refreshing until block true ✓ (0.03s)
      Stamp the LBC BCR Dil 2 ✓ (4.58s)
    } ✓ (4.61s)
    Process the LBC BCR Dil 2 plate (DN623963N) {
      Fill in hamilton LBC BCR Enrich2 2XSPRI => LBC BCR Dil 2 ✓ (3.12s)
    } ✓ (6.23s)
    Process the LBC BCR Post Lig 1XSPRI plate {
      Fill in the custom tagged plate page ✓ (5.79s)
LBC BCR Post Lig 1XSPRI = DN623964O
      Fill in hamilton LBC BCR Dil 2 => LBC BCR Post Lig 1XSPRI ✓ (2.44s)
      Stamp the LBC BCR Post PCR ✓ (5.31s)
    } ✓ (15.77s)
    Process the LBC BCR Post PCR plate (DN623965P) ✓ (11.68s)
    Process the LBC BCR LibPS tubes ✓ (11.85s)
  } OK (311.82s)
} (311.83s)
Following the Bespoke Chromium Aggregation and 3pv3 pipelines {
  96 well {
    Build submission ✓ (5.42s)
    Build tag group ✓ (0.21s)
    Log in ✓ (1.39s)
    Process the LBC Stock plate (DN623966Q) {
      Refreshing until block true ✓ (7.05s)
    } ✓ (8.97s)
    Process the LBC Aggregate plate {
      Fill in the ten stamp page ✓ (7.22s)
    } ✓ (12.42s)
    Process the LBC Cherrypick plate {
      Fill in the ten stamp page ✓ (7.58s)
      Fill in hamilton LBC Aggregate => LBC Cherrypick ✓ (4.78s)
    } ✓ (15.45s)
    Build submission for chromium library creation [3pv3 Submission id = 113961]
✓ (2.06s)
    Add concentrations to plate Number of well concentrations written = 90
✓ (1.39s)
    Continue processing the LBC Cherrypick plate (DN623968S) {
      Refreshing until block true ✓ (17.25s)
      Stamp the LBC 3pV3 GEX Dil ✓ (5.28s)
    } ✓ (22.53s)
    Process the LBC 3pV3 GEX Dil plate (DN623969T) {
      Fill in hamilton LBC Cherrypick => LBC 3pV3 GEX Dil ✓ (2.98s)
      Stamp the LBC 3pV3 GEX Frag 2XP ✓ (4.12s)
    } ✓ (9.99s)
    Process the LBC 3pV3 GEX Frag 2XP plate (DN623970M) {
      Fill in hamilton LBC 3pV3 GEX Dil => LBC 3pV3 GEX Frag 2XP ✓ (3.18s)
    } ✓ (6.60s)
    Process the LBC 3pV3 GEX LigXP plate {
      Fill in the custom tagged plate page ✓ (7.54s)
      Fill in hamilton LBC 3pV3 GEX Frag 2XP => LBC 3pV3 GEX LigXP ✓ (3.46s)
      Stamp the LBC 3pV3 GEX PCR 2XP ✓ (5.28s)
    } ✓ (18.61s)
    Process the LBC 3pV3 GEX PCR 2XP plate (DN623972O) ✓ (13.38s)
    Process the LBC 3pV3 GLibPS tubes ✓ (12.58s)
  } OK (131.44s)
} (131.44s)
Following the WGS pipeline {
  96 well {
    Build submissions ✓ (5.43s)
    Log in ✓ (1.33s)
    Process LB Cherrypick Plate (DN623973P) {
      Refreshing until submission built ✓ (6.92s)
      Stamp the LB Shear ✓ (6.71s)
    } ✓ (14.98s)
    Process LB Shear Plate (DN623975R) {
      Fill in bravo LB Cherrypick => LB Shear ✓ (3.26s)
      Stamp the LB Post Shear ✓ (5.74s)
    } ✓ (11.20s)
    Process LB Post Shear (DN623976S) {
      Fill in bravo LB Shear => LB Post Shear ✓ (2.18s)
      Stamp the LB End Prep ✓ (5.81s)
    } ✓ (10.35s)
    Process LB End Prep (DN623977T) {
      Fill in bravo LB Post Shear => LB End Prep ✓ (2.38s)
      Fill in bravo LB End Prep ✓ (2.26s)
      Create tag plate ✓ (5.81s)
    } ✓ (16.39s)
    Process LB Lib PCR (DN623974Q) {
      Fill in bravo LB End Prep => LB Lib PCR ✓ (2.16s)
      Stamp the LB Lib PCR-XP ✓ (5.98s)
    } ✓ (9.96s)
    Process the LB Lib PCR-XP plate (DN623978U) {
      Fill in bravo LB Lib PCR => LB Lib PCR XP ✓ (2.15s)
    } ✓ (14.46s)
    Process the final pool tubes ✓ (12.88s)
  } OK (98.19s)
} (98.19s)
Following the PCR Free pipeline {
  96 well OK (0.79s)
  with 4 submissions {
    384 well {
      Build submissions ✓ (21.15s)
      Log in ✓ (1.25s)
      Process PF Cherrypicked to PF Post Shear (DN623979V) {
        Refreshing until block true ✓ (0.11s)
        Stamp the PF Shear ✓ (7.11s)
        Fill in bravo PF Cherrypicked => PF Shear ✓ (3.47s)
        Stamp the PF Post Shear ✓ (6.04s)
        Fill in bravo PF Shear => PF Post Shear ✓ (2.29s)
      } ✓ (23.96s)
      Process PF Cherrypicked to PF Post Shear (DN623980O) {
        Refreshing until block true ✓ (0.07s)
        Stamp the PF Shear ✓ (6.50s)
        Fill in bravo PF Cherrypicked => PF Shear ✓ (3.44s)
        Stamp the PF Post Shear ✓ (5.80s)
        Fill in bravo PF Shear => PF Post Shear ✓ (2.17s)
      } ✓ (22.75s)
      Process PF Cherrypicked to PF Post Shear (DN623981P) {
        Refreshing until block true ✓ (0.06s)
        Stamp the PF Shear ✓ (7.00s)
        Fill in bravo PF Cherrypicked => PF Shear ✓ (3.69s)
        Stamp the PF Post Shear ✓ (5.89s)
        Fill in bravo PF Shear => PF Post Shear ✓ (2.42s)
      } ✓ (23.33s)
      Process PF Cherrypicked to PF Post Shear (DN623982Q) {
        Refreshing until block true ✓ (0.10s)
        Stamp the PF Shear ✓ (6.00s)
        Fill in bravo PF Cherrypicked => PF Shear ✓ (3.85s)
        Stamp the PF Post Shear ✓ (5.79s)
        Fill in bravo PF Shear => PF Post Shear ✓ (2.53s)
      } ✓ (23.18s)
      QuadrantStamp creation ✓ (25.67s)
      Fill in Hamilton STAR-384 PF-Post Shear => PF-384 Post Shear XP ✓ (7.12s)
      Stamp the PF-384 End Prep ✓ (20.49s)
      Fill in bravo PF-384 Post Shear XP => PF-384 End Prep ✓ (4.32s)
      Fill in Bravo PF-384 End Prep End Preparation ✓ (4.06s)
      Create tag plate ✓ (17.73s)
      Stamp the PF-384 Lib XP2 ✓ (23.10s)
      Fill in Bravo PF-384 End Prep to PF-384 Lib XP2 ✓ (6.38s)
      Create PF Lib Q-XP2 plates (DN623994U) ✓ (30.34s)
      Fill in Bravo PF-384 Lib XP2 => PF-Lib Q-XP2 ✓ (7.16s)
      Process end of pipeline (DN623995V) ✓ (31.09s)
      Process end of pipeline (DN623996W) ✓ (27.52s)
      Process end of pipeline (DN623997A) ✓ (28.26s)
      Process end of pipeline (DN623998B) ✓ (27.26s)
    } OK (402.90s)
  } (402.90s)
} (403.69s)
Following the Bespoke PCR pipeline {
  96 well {
    Build submissions ✓ (5.49s)
    Build tag group ✓ (0.23s)
    Log in ✓ (1.06s)
    Process LBB Cherrypick Plate {
      Refreshing until block true ✓ (6.69s)
      Stamp the LBB Ligation ✓ (7.34s)
    } ✓ (15.42s)
    Process the LBB Ligation plate ✓ (5.16s)
    Process the LBB Lib PCR-XP plate {
      Fill in the custom tagged plate page ✓ (6.62s)
    } ✓ (20.26s)
    Process the final pool tubes ✓ (12.13s)
  } OK (60.17s)
} (60.17s)
Following the Bespoke PCR Free pipeline {
  96 well {
    Build submissions ✓ (5.43s)
    Log in ✓ (1.04s)
    Process LBB Cherrypick Plate {
      Refreshing until block true ✓ (6.71s)
    } ✓ (9.05s)
    Process LBB Ligation Tagged plate {
      Fill in the custom tagged plate page ✓ (6.34s)
      Stamp the LBB Lib-XP ✓ (7.02s)
    } ✓ (18.10s)
    Process the LBB Lib-XP plate ✓ (14.00s)
    Process the final pool tubes ✓ (13.41s)
  } OK (61.44s)
} (61.44s)
Following the GBS pipeline {
  96 well {
    Log in ✓ (1.65s)
    Build submissions ✓ (21.38s)
    Process the GBS-96 stock (DN624006E) {
      Refreshing until submission built ✓ (6.33s)
      QuadrantStamp creation ✓ (27.48s)
    } ✓ (35.56s)
    Process the GBS PCR1 (DN624010A) {
      Fill in Mosquito GBS-96 Stock => GBS PCR1 ✓ (11.61s)
      Create tag plate ✓ (19.55s)
    } ✓ (42.89s)
    Process GBS PCR2 (DN624011B) {
      Fill in the pool page ✓ (14.31s)
    } ✓ (21.23s)
    Process GBS PCR2 Pool Stock (3981556560675) ✓ (28.79s)
    Process GBS PCR Pool (3981556561689) ✓ (26.46s)
    Process GBS PCR Pool Selected (3981556562693) {
      Fill in the tube pool page ✓ (25.57s)
    } ✓ (35.13s)
    Process GBS MiSeql Pool (3981556563706) ✓ (29.68s)
  } OK (242.91s)
} (242.91s)
Following the ISC pipeline {
  96 well {
    Build submissions ✓ (5.51s)
    Log in ✓ (1.04s)
    Process LB Cherrypick Plate (DN624012C) {
      Refreshing until submission built ✓ (6.61s)
      Stamp the LB Shear ✓ (7.38s)
    } ✓ (15.32s)
    Process LB Shear Plate (DN624014E) {
      Fill in bravo LB Cherrypick => LB Shear ✓ (3.26s)
      Stamp the LB Post Shear ✓ (5.65s)
    } ✓ (11.09s)
    Process LB Post Shear (DN624015F) {
      Fill in bravo LB Shear => LB Post Shear ✓ (2.11s)
      Stamp the LB End Prep ✓ (5.93s)
    } ✓ (10.16s)
    Process LB End Prep (DN624016G) {
      Fill in bravo LB Post Shear => LB End Prep ✓ (2.47s)
      Fill in bravo LB End Prep ✓ (2.30s)
      Create tag plate ✓ (5.62s)
    } ✓ (16.22s)
    Process LB Lib PCR (DN624013D) {
      Fill in bravo LB End Prep => LB Lib PCR ✓ (2.38s)
      Stamp the LB Lib PCR-XP ✓ (5.45s)
    } ✓ (9.58s)
    Process the LB Lib PCR-XP plate (DN624017H) {
      Fill in bravo LB Lib PCR => LB Lib PCR XP ✓ (2.12s)
    } ✓ (4.52s)
    Create the LB Lib PrePool plate {
      Fill in the pre pool page ✓ (5.59s)
    } ✓ (5.59s)
    Process the LB Lib PrePool plate (DN624018I) {
      Fill in nx-8 Lib PCR-XP => LB Lib PrePool ✓ (2.84s)
    } ✓ (5.86s)
    Create the LB Hyb plate ✓ (4.53s)
    Process the LB Hyb plate (DN624019J) {
      Fill in nx-8 LB Lib PrePool => LB Hyb ✓ (1.79s)
      Stamp the LB Cap Lib ✓ (4.17s)
    } ✓ (7.67s)
    Process the LB Cap Lib plate (DN624020C) {
      Fill in bravo LB Hyb => LB Cap Lib ✓ (2.07s)
      Stamp the LB Cap Lib PCR ✓ (3.86s)
    } ✓ (7.67s)
    Process the LB Cap Lib PCR plate (DN624021D) {
      Fill in bravo LB Cap Lib => LB Cap Lib PCR ✓ (3.49s)
      Stamp the LB Cap Lib PCR-XP ✓ (4.39s)
    } ✓ (9.66s)
    Process the LB Cap Lib PCR-XP (DN624022E) {
      Fill in nx-96 LB Cap Lib PCR => LB Cap Lib PCR-XP ✓ (3.22s)
      Stamp the LB Cap Lib Pool ✓ (6.97s)
    } ✓ (15.73s)
    Process the LB Cap Lib Pool (DN624023F) {
      Fill in nx-8 LB Cap Lib PCR-XP => LB Cap Lib Pool ✓ (2.56s)
    } ✓ (7.95s)
    Process the final tube lib_pool_tube: 3981556564710
✓ (4.46s)
  } OK (143.72s)
} (143.72s)
Following the Bespoke Chromium manual 3 prime v2 pipeline {
  96 well {
    Build submissions ✓ (5.25s)
    Build tag group ✓ (0.19s)
    Log in ✓ (1.38s)
    Process LBB Cherrypick Plate {
      Refreshing until block true ✓ (6.67s)
    } ✓ (9.00s)
    Process LBB Chromium Tagged plate {
      Fill in the custom tagged plate page ✓ (7.82s)
      Stamp the LBB Lib-XP ✓ (7.94s)
    } ✓ (20.05s)
    Process the LBB Lib-XP plate (DN624026I) ✓ (20.77s)
    Process the final pool tubes ✓ (24.55s)
  } OK (81.40s)
} (81.40s)
Following the Single Cell pipeline {
  sc-RNA 384 OK (1.07s)
} (1.07s)
Following the high throughput Duplex-Seq pipeline {
  96 well {
    Build tag group ✓ (0.24s)
    Build submission [Duplex-Seq Submission id = 113976]
✓ (4.97s)
    Build tag layout template ✓ (0.20s)
    Log in ✓ (1.10s)
    Process the LDS Cherrypick plate (DN624027J) {
      Refreshing until block true ✓ (6.50s)
      Stamp the LDS Stock XP ✓ (6.58s)
    } ✓ (14.30s)
    Process the LDS Stock XP plate (DN624029L) {
      Stamp the LDS AL Lib ✓ (6.13s)
    } ✓ (10.42s)
    Add concentrations to LDS AL Lib plate (DN624030E) Number of well concentrations written = 90
✓ (1.52s)
    Fetch plate well information for LDS Al Lib plate (DN624030E) Wells with aliquots = A1, B1, C1, D1, E1, F1, G1, H1, A2, B2, C2, E2, F2, H2, A3, B3, C3, D3, E3, F3, G3, H3, A4, B4, C4, E4, F4, G4, H4, A5, B5, C5, D5, E5, F5, G5, H5, A6, B6, C6, D6, E6, F6, G6, H6, A7, B7, C7, D7, E7, F7, G7, H7, A8, B8, C8, D8, E8, F8, G8, H8, A9, B9, C9, D9, E9, F9, G9, H9, A10, B10, D10, E10, F10, G10, H10, A11, C11, D11, E11, F11, G11, H11, B12, C12, D12, E12, F12, G12, H12
✓ (0.43s)
    Process the LDS AL Lib plate (DN624030E) {
      Generate the customer upload file ✓ (0.00s)
      Fill in the duplex seq file upload page ✗ (10.18s)
    } ✗ (20.18s)
  } PENDING: pipeline deployment (54.28s)
} (54.28s)

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Following the high throughput Duplex-Seq pipeline 96 well
     # pipeline deployment
     Failure/Error: expect(page).to have_content('File upload')
       expected to find text "File upload" in "Limber\nstaging\nPlate or Tube Barcode\nCurrently logged in as, Test User Log Out\nNotice\nNew empty labware added to the system.\nLDS AL Lib Dil Pending\n  1 2 3 4 5 6 7 8 9 10 11 12\nA\nB\nC\nD\nE\nF\nG\nH\nSummary\nChildren\nPooling\nSamples\nFiles\nComments 0\nBarcode\nDN624031F\nNumber of wells\n90/96\nPlate type\nLDS AL Lib Dil\nCurrent plate state\npending\nInput plate barcode\nDN624027J\nPCR Cycles\n0\nCreated on\n2020-04-03\nPrint plate label\nBarcode Printer\nd304bc\np301bc\ng316bc\ng214bc\ng216abc\ng311bc2\ng317bc\ng312bc2\nb213bc\nk115bc2\ne307bc\nf225bc\nh105bc2\nh106bc\nk114bc\ndnapbc2\nh218bc\nscgcf1\nscgcf2\nh136bc\nAttach files\nSelect a file above, then click upload. Uploaded files will appear in the files tab.\nSuggested Actions\nDownload Hamilton AL Lib to Dilution CSV\nRobots\nhamilton LDS AL Lib => LDS AL Lib Dil\nAdding a Comment\nAdd Comment to Sequencescape\nOther Actions\nOther changes\nChange state to\ncancelled\nReason for cancellation\nContaminated\nIncorrect protocol used\nNot required\nLimber WIP [staging] 20200402154926 uat_gpl373_bed_verify_rt_to_pcr@78bc994 limb-uat"
     # ./spec/support/limber_helpers.rb:341:in `block in fill_in_the_duplex_seq_file_upload_page'
     # ./spec/support/utility_helpers.rb:33:in `block in step'
     # /Users/jg16/.rvm/gems/ruby-2.6.3@integration-suite/gems/rspec-longrun-3.1.0/lib/rspec/longrun/dsl.rb:9:in `step'
     # ./spec/support/utility_helpers.rb:32:in `step'
     # ./spec/support/limber_helpers.rb:340:in `fill_in_the_duplex_seq_file_upload_page'
     # ./spec/limber/duplex_seq_pipeline_spec.rb:138:in `block (3 levels) in <top (required)>'
     # ./spec/support/utility_helpers.rb:33:in `block in step'
     # /Users/jg16/.rvm/gems/ruby-2.6.3@integration-suite/gems/rspec-longrun-3.1.0/lib/rspec/longrun/dsl.rb:9:in `step'
     # ./spec/support/utility_helpers.rb:32:in `step'
     # ./spec/limber/duplex_seq_pipeline_spec.rb:120:in `block (2 levels) in <top (required)>'

Top 10 slowest examples (1630.78 seconds, 96.7% of total time):
  Following the PCR Free pipeline with 4 submissions 384 well
    402.9 seconds ./spec/limber/pcr_free_pipeline_spec.rb:43
  Following the Bespoke Chromium Aggregation and 5p VDJ pipelines 96 well
    311.82 seconds ./spec/limber/bespoke_chromium_5p_vdj_pipeline_spec.rb:38
  Following the GBS pipeline 96 well
    242.91 seconds ./spec/limber/gbs_pipeline_spec.rb:28
  Following the ISC pipeline 96 well
    143.72 seconds ./spec/limber/isc_pipeline_spec.rb:28
  Following the Bespoke Chromium Aggregation and 3pv3 pipelines 96 well
    131.44 seconds ./spec/limber/bespoke_chromium_3pv3_pipeline_spec.rb:38
  Following the WGS pipeline 96 well
    98.19 seconds ./spec/limber/wgs_pipeline_spec.rb:28
  Following the high throughput Heron(96-well) pipeline 96 well
    96.8 seconds ./spec/limber/heron_pipeline_spec.rb:105
  Following the Bespoke Chromium manual 3 prime v2 pipeline 96 well
    81.4 seconds ./spec/limber/bespoke_chromium_manual_3pv2_pipeline_spec.rb:39
  Following the Bespoke PCR Free pipeline 96 well
    61.44 seconds ./spec/limber/bespoke_pcr_free_pipeline_spec.rb:24
  Following the Bespoke PCR pipeline 96 well
    60.17 seconds ./spec/limber/bespoke_pcr_pipeline_spec.rb:31

Top 10 slowest example groups:
  Following the Bespoke Chromium Aggregation and 5p VDJ pipelines
    311.83 seconds average (311.83 seconds / 1 example) ./spec/limber/bespoke_chromium_5p_vdj_pipeline_spec.rb:3
  Following the GBS pipeline
    242.91 seconds average (242.91 seconds / 1 example) ./spec/limber/gbs_pipeline_spec.rb:3
  Following the PCR Free pipeline
    201.85 seconds average (403.69 seconds / 2 examples) ./spec/limber/pcr_free_pipeline_spec.rb:3
  Following the ISC pipeline
    143.72 seconds average (143.72 seconds / 1 example) ./spec/limber/isc_pipeline_spec.rb:3
  Following the Bespoke Chromium Aggregation and 3pv3 pipelines
    131.44 seconds average (131.44 seconds / 1 example) ./spec/limber/bespoke_chromium_3pv3_pipeline_spec.rb:3
  Following the WGS pipeline
    98.19 seconds average (98.19 seconds / 1 example) ./spec/limber/wgs_pipeline_spec.rb:3
  Following the high throughput Heron(96-well) pipeline
    96.8 seconds average (96.8 seconds / 1 example) ./spec/limber/heron_pipeline_spec.rb:3
  Following the Bespoke Chromium manual 3 prime v2 pipeline
    81.4 seconds average (81.4 seconds / 1 example) ./spec/limber/bespoke_chromium_manual_3pv2_pipeline_spec.rb:3
  Following the Bespoke PCR Free pipeline
    61.44 seconds average (61.44 seconds / 1 example) ./spec/limber/bespoke_pcr_free_pipeline_spec.rb:3
  Following the Bespoke PCR pipeline
    60.17 seconds average (60.17 seconds / 1 example) ./spec/limber/bespoke_pcr_pipeline_spec.rb:3

Finished in 28 minutes 7 seconds (files took 1.14 seconds to load)
13 examples, 0 failures, 1 pending

Randomized with seed 56123```

I'll be extracting the longest steps shortly

**Comment by JamesGlover** [comment]
So pulling out the times, and ignoring those that cover entire pipelines:

A multi-step process, as covers processing a whole plate, but the slowest of the bunch.
```
Process the GBS PCR1 (DN624010A) {
      Fill in Mosquito GBS-96 Stock => GBS PCR1 ✓ (11.61s)
      Create tag plate ✓ (19.55s)
    } ✓ (42.89s)
```

**Comment by JamesGlover** [comment]
Another multi-step process, and can largely discount waiting for the submission to build, but that quadrant stamp is a little slow. (This does cover scanning everything in though, not just clicking 'create')
```
Process the GBS-96 stock (DN624006E) {
      Refreshing until submission built ✓ (6.33s)
      QuadrantStamp creation ✓ (27.48s)
    } ✓ (35.56s)
```

**Comment by JamesGlover** [comment]
Another slowish multi-step process. 
```
Process GBS PCR Pool Selected (3981556562693) {
      Fill in the tube pool page ✓ (25.57s)
    } ✓ (35.13s)
```

**Comment by JamesGlover** [comment]
There are a number of long 'process end of pipeline' processes, but these cover lots of actions and I'll add a bit more granularity to the tracking.

**Comment by JamesGlover** [comment]
Our longest single step step:
`Create PF Lib Q-XP2 plates (DN623994U) ✓ (30.34s)`

**Comment by stevieing** [comment]
So it turns out that Rack::MiniProfiler is already in Sequencescape. If you look in the top right of the page you can see the timings. If you expand that it will give you more information about the request. It is really only useful for checking what goes on during live requests. You can also add another gem flamegraph and then in your request add ?pp=flamegraph which gives you a graph of where the time is spent. This will only tell you about Rails stuff so it doesn't seem to give any information about any of sequencescaoe specific code. For our purposes we would need to add it in Limber but then it would only give information about Limber requests. My conclusion is that it is going to be of no use for us for this story.
